#BlueJ properties. Settings in this file override "bluej.defs"
#Tue Mar 10 08:44:11 CET 2026
blackbox.uuid=db293900-e5fa-48f6-9052-a86feb289375
bluej.editor.fontsize=12
bluej.editor.stride.sidebarShowing=true
bluej.openPackage1=C\:\\Users\\Vegova\\Desktop\\vislice_demo_2
bluej.recentProject0=C\:\\Users\\Vegova\\Desktop\\vislice_demo_2
bluej.startWithTextEval=false
bluej.terminal.x=16
bluej.terminal.y=16
bluej.uid=fa8cdfb4-5a09-44c1-b531-fb2c7489076e
extensions.org.bluej.extensions.submitter.Submitter.settings.saslrealm=
session.numeditors.java=1
session.numeditors.stride=0
